### ISSUE TITLE
Switch out Jazz identicons for Mist identicons

### ISSUE THREAD

**Issue by fabioberger** [0xProject/website#1]
Starting point: https://github.com/0xProject/0x/blob/development/src/client/app/components/Identicon.jsx

**Comment by bonen** [comment]
@fabioberger I see the 0xOTC application is now using identicons that match the mist identicons. Have you found out what the correct settings are? We would also like to use them in our real estate trading dapp. Thanks in advance for your help!

**Comment by LogvinovLeon** [comment]
@bomen We started using https://github.com/ethereum/blockies.
It's the same as parity and etherscan uses. You can check the code in the parity repo.

**Comment by LogvinovLeon** [comment]
https://github.com/paritytech/parity/blob/8404edb656693270ec1cd3956d204f625d28ec7c/js/src/api/util/identity.js

**Comment by bonen** [comment]
@LogvinovLeon Thanks a lot. Npm installing blockies@0.0.2 with seed address.toLowerCase(), scale 8 and size 8 did the trick!
