### ISSUE TITLE
Inconsistency in allowance language

### ISSUE THREAD

**Issue by miohtama** [0xProject/website#130]
The Balances screen uses language "Trade Allowances"

<img width="829" alt="image" src="https://user-images.githubusercontent.com/49922/30422256-160af8da-9948-11e7-9d3c-9266366ae300.png">

However the Generate and order screen uses language "Increase balance"

<img width="383" alt="image" src="https://user-images.githubusercontent.com/49922/30422434-9e126c7c-9948-11e7-8558-503660a9ffcd.png">

When it asks user to "Increase the balance" the user gets confused.

**Comment by fabioberger** [comment]
@miohtama where is "Trade Allowances"? Allowance and balance are two separate concepts.
