### ISSUE TITLE
Infrastructure credits page is broken

### ISSUE THREAD

**Issue by chriskalani** [0xProject/website#194]
Safari and Chrome

See here: https://0x.org/credits

<img width="1867" alt="Screen Shot 2020-01-13 at 2 15 42 PM" src="https://user-images.githubusercontent.com/263522/72296738-3338ef00-360f-11ea-9b1d-5e6cb0f97d9d.png">

**Comment by johnrjj** [comment]
https://github.com/0xProject/website/pull/195

**Comment by chriskalani** [comment]
Thank you!
