### ISSUE TITLE
Host private Parity node

### ISSUE THREAD

**Issue by willwarren89** [0xProject/website#38]
Host a private Parity node rather than rely on Infura.

**Comment by fabioberger** [comment]
This will speed things up for visitors browsing the DApp without Web3 injected in their browsers (Metamask, Mist, Parity Signer). But for Metamask users, I'm pretty sure they have to use the Kovan node that Metamask is set up to use.

**Comment by willwarren89** [comment]
Is there a way to set up subproviders? Private node for monitoring/serving blockchain state, MetaMask for signing?
