### ISSUE TITLE
Add Kim and JJ to the website

### ISSUE THREAD

**Issue by chriskalani** [0xProject/website#69]
Add to team page: https://0x.org/about/team

**John Johnson**
Front-end Engineer

**Kim Persson**
Front-end Engineer

(feel free to write your title how you want, feel free to discuss)

![johnj](https://user-images.githubusercontent.com/263522/70003812-2e195800-1519-11ea-8725-6ee6d35b12a4.jpg)
![kimp](https://user-images.githubusercontent.com/263522/70003813-2e195800-1519-11ea-8fac-fde4913b9aa9.jpg)

**Comment by johnrjj** [comment]
Addressed in https://github.com/0xProject/website/pull/70
