### ISSUE TITLE
erc20 token MTL addition to OTC DaPP

### ISSUE THREAD

**Issue by spidey6600** [0xProject/website#99]
Request to adding MTL token for tokenswap on OTC DaPP. The project metalpay.com has gained popularity since its tokensale last month and has tremendous potential. In addition its is great demand right now with the upcoming launch of alpha this week and beta next month. 

Please add MTL to the OTC token list.

**Comment by quantumdwayne** [comment]
Commenting in support of getting MTL added to the OTC dAPP.

**Comment by cyperx** [comment]
This would be amazing!!! please support MTL

**Comment by parthpankajtiwary** [comment]
Commenting in support of MTL. Would love to see it on the OTC token list!

**Comment by fabioberger** [comment]
FYI, anyone can add any custom token to OTC. Open the token picker and select "Add custom token". We do plan on adding plenty more tokens to OTC but until we do, please use the custom token feature!
